# Your Name or Company
title: 

# Description of your website. This is used for social sharing.
description:

# A brief blurb about yourself
content: 

# Add your social links
social:
  - platform: naver.smartstore
    url: https://smartstore.naver.com/
  - platform: ohou.se
    url: https://ohou.se/
  - platform: 29cm
    url: https://www.29cm.co.kr/home/
  - platform: MUSINSA
    url: https://www.musinsa.com/

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
